### ISSUE TITLE
4.9.89 audio regression

### ISSUE THREAD

**Issue by warped-rudi** [SolidRun/linux-fslc#56] opened 2018-03-24 08:28 UTC
With 4.9.89 Kodi will no longer output any sound. The log says something like:

`ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover`
`ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)`
`ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover`
`ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover`
`ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)`
`ERROR: CAESinkALSA::HandleError(snd_pcm_writei(2)) - snd_pcm_writei returned -5 (Input/output error)`
`ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover`
`ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)`
`ERROR: CAESinkALSA::HandleError(snd_pcm_writei(2)) - snd_pcm_writei returned -5 (Input/output error)`

It seems to be a generic issue because this does not only happen on HDMI but on *all* audio devices. I'm trying to figure out which patch introduced this (not really bisecting, but going backwards one revision after the other).

**Comment by jnettlet** [comment] 2018-03-24 08:53
check the sdma patches.  There were conflicting merges.  Nothing major but the mainline patches could be causing errors caused by NXP's firmware.

**Comment by warped-rudi** [comment] 2018-03-24 10:13
Argg! Something is fundamentally wrong here. If I downgrade both _imx-sdma.c_ and _fsl-edma.c_ I get sound back. The change in imx-sdma.c looks fishy to me. The newly introduced function sdma_disable_channel_with_delay() is by no means equivalent to sdma_terminate_all() plus a delay of 1ms. Not sure what's wrong with fsl-edma.c. Still investigating...

BTW, thanks for the board. It arrived last week.

**Comment by jnettlet** [comment] 2018-03-24 10:54
Most likely I will just revert those two commits.  Personally I am not even
sure why they were tagged to be brought back to the LTS kernels

**Comment by warped-rudi** [comment] 2018-03-24 11:28
A little mistake on my side: _fsl-edma.c_ is not involved. As for sdma_disable_channel_with_delay(): For me it looks like this functions should be named sdma_terminate_all_with_delay() and should wait that stupid millisecond after calling sdma_terminate_all() to do the real work...

**Comment by jnettlet** [comment] 2018-03-24 13:34
I reverted the problematic patch.  This seems to be an upstream problem since NXP has a completely different method for terminating the DMA channel.  This is tested and fixed with the Reverted patch.

**Closed as completed by jnettlet** 2018-03-24 13:34 UTC
